name: Testmo to Slack

on:
  workflow_dispatch:

jobs:
  send_testmo_results:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get latest Testmo automation run
        id: get_run
        run: |
          echo "Fetching latest automation run from Testmo..."
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.TESTMO_API_TOKEN }}" \
            "https://${{ secrets.TESTMO_BASE_URL }}/api/v1/projects/1/automation/runs?limit=1")

          echo "API Response:"
          echo "$response"

          echo "$response" > latest_run.json

          # Extract total runs count
          total_runs=$(jq -r '.total' latest_run.json)

          # Extract latest run ID and status code from first element in 'result'
          latest_id=$(jq -r '.result[0].id' latest_run.json)
          latest_status_code=$(jq -r '.result[0].status' latest_run.json)

          # Translate status code to text
          case $latest_status_code in
            1) latest_status="Queued" ;;
            2) latest_status="Passed" ;;
            3) latest_status="Failed" ;;
            4) latest_status="Aborted" ;;
            *) latest_status="Unknown" ;;
          esac

          # Fetch detailed info for latest run to get more data
          detailed_response=$(curl -s -H "Authorization: Bearer ${{ secrets.TESTMO_API_TOKEN }}" \
            "https://${{ secrets.TESTMO_BASE_URL }}/api/v1/automation/runs/${latest_id}")

          echo "$detailed_response" > detailed_run.json

          # Extract required fields from detailed run response
          run_name=$(jq -r '.name' detailed_run.json)
          success_count=$(jq -r '.success_count' detailed_run.json)
          failure_count=$(jq -r '.failure_count' detailed_run.json)
          completed_count=$(jq -r '.completed_count' detailed_run.json)
          total_count=$(jq -r '.total_count' detailed_run.json)

          # Export these as outputs
          echo "total_runs=$total_runs" >> $GITHUB_OUTPUT
          echo "latest_id=$latest_id" >> $GITHUB_OUTPUT
          echo "latest_status=$latest_status" >> $GITHUB_OUTPUT
          echo "run_name=$run_name" >> $GITHUB_OUTPUT
          echo "success_count=$success_count" >> $GITHUB_OUTPUT
          echo "failure_count=$failure_count" >> $GITHUB_OUTPUT
          echo "completed_count=$completed_count" >> $GITHUB_OUTPUT
          echo "total_count=$total_count" >> $GITHUB_OUTPUT



      - name: Send Slack message
        run: |
          if [ -z "${{ steps.get_run.outputs.latest_id }}" ] || [ "${{ steps.get_run.outputs.latest_id }}" = "null" ]; then
            echo "No run found, skipping Slack notification."
            exit 0
          fi

          slack_message=":mega: Testmo Automation Runs: Total = ${{ steps.get_run.outputs.total_runs }}
          :calendar: Latest Run ID: #${{ steps.get_run.outputs.latest_id }} — ${{ steps.get_run.outputs.run_name }}
          :bar_chart: Status: ${{ steps.get_run.outputs.latest_status }}
          :white_check_mark: Passed: ${{ steps.get_run.outputs.success_count }}
          :x: Failed: ${{ steps.get_run.outputs.failure_count }}
          :clipboard: Completed: ${{ steps.get_run.outputs.completed_count }} / ${{ steps.get_run.outputs.total_count }}
          :link: <https://${{ secrets.TESTMO_BASE_URL }}/automation/runs/${{ steps.get_run.outputs.latest_id }}|View Latest Run>"

          payload=$(jq -n --arg t "$slack_message" '{text: $t}')

          curl -X POST -H "Content-Type: application/json" --data "$payload" "${{ secrets.SLACK_WEBHOOK_URL }}"

